---
title: Joey Burzynski
timezone: America/New_York
collections:
  view:
    title: Latest
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: joey@marketkarma.com
description: A 30-something living in Miami Beach. Founder of MarketKarma and CouponMate.
baseurl: 
url: https://joeyburzynski.github.io/
twitter_username: JoeyBurzynski
github_username: JoeyBurzynski
markdown: kramdown
